


















































}    }        });            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());        RateLimiter::for('api', function (Request $request) {    {    protected function configureRateLimiting()     */     * @return void     *     * Configure the rate limiters for the application.    /**    }        });                ->group(base_path('routes/api.php'));                ->namespace($this->namespace)                ->prefix('api')            Route::middleware('api')                ->group(base_path('routes/web.php'));                ->namespace($this->namespace)            Route::middleware('web')        $this->routes(function () {        $this->configureRateLimiting();    {    public function boot()     */     * @return void     *     * Define your route model bindings, pattern filters, etc.    /**    public const HOME = '/dashboard';     */     * @var string     *     * This is used by Laravel authentication to redirect users after login.     *     * The path to the "home" route for your application.    /**{class RouteServiceProvider extends ServiceProvideruse Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;use Illuminate\Support\Facades\Route;namespace App\Providers;<?php